In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Parameters 

Lx = 6
Ly = 3
K = 2 
J = 1 
W = 4 

N = Lx * Ly 

print ("Total number of sites =", N)

# Create random connection matrices T 

T = []

np.random.seed(0)

for x in range(Lx-1):
    
    Tx = np.zeros((Ly, Ly), dtype=int)

    for j in range(Ly):

        rows = np.random.choice(Ly, K, replace=False)

        for i in rows:
            Tx[i,j] = 1 
    
    T.append(Tx)

    print(f"\nConnection matrix T({x+1}, {x+2}):")
    print(Tx)


# Create random onsite potentials

epsilon = np.random.uniform(-W/2, W/2, size=(Lx, Ly))

print("\nOnsite potential epsilon:")
print(epsilon)

# Create the Hamiltonian 

H = np.zeros((N, N))

# Put onsite potentails on the diagonal 

for x in range(Lx):
    for y in range(Ly):

        site = x * Ly + y 

        H[site, site] = epsilon[x, y]

    


Total number of sites = 18

Connection matrix T(1, 2):
[[0 1 1]
 [1 0 0]
 [1 1 1]]

Connection matrix T(2, 3):
[[1 0 1]
 [0 1 1]
 [1 1 0]]

Connection matrix T(3, 4):
[[0 1 1]
 [1 1 1]
 [1 0 0]]

Connection matrix T(4, 5):
[[1 1 1]
 [1 0 0]
 [0 1 1]]

Connection matrix T(5, 6):
[[0 0 0]
 [1 1 1]
 [1 1 1]]

Onsite potential epsilon:
[[ 1.82862064 -1.43859688  1.48034903]
 [-0.10556782  1.20364301  0.08190992]
 [ 0.71551812  0.88253062  0.32807917]
 [ 0.14949292  1.0344625  -1.57636957]
 [-0.10559832 -1.25467063  0.94767271]
 [-1.13379858 -1.45912731 -0.70343597]]
